hipspy/hips

docs/develop.rst
docs/drawing_algo.rst
docs/index.rst

This PR:
- Changes the table of content and sidebar as shown in the screenshot
- Moves the "tile drawing algorithm page" into the developer docs section (as most users won't read through it) and shortens the headings so that they are readable in the table of content side bar. Otherwise it's just whitespace formatting changes. Hope that change is OK @tboch .
- Adds a very small page with developer info (we can extend later)

Small docs update

---

.travis.yml
docs/index.rst
docs/installation.rst
docs/references.txt
setup.py

As discussed offline, at least for now we'll use `scikit-image` for tile drawing. So I'm adding it as a dependency here in this PR. If this dependency is an issue for some users, we can always spend the effort to replace it just by scipy or pure Numpy later.

Add scikit-image as dependency

---

.rtd-environment.yml
.travis.yml
setup.cfg
setup.py

Now that healpy 1.10 is available for Python 3.6 on conda-forge (which we use for testing on travis-ci), see https://github.com/conda-forge/healpy-feedstock/pull/4, I'd like to try and update our CI from Python 3.5 to 3.6
This pull request:

Update dependencies and CI settings

---

.travis.yml
docs/api.rst
docs/installation.rst
docs/references.txt
setup.py

In #24 is using PIL/Pillow to read JPEG tiles. This is a reminder issue that we need to declare and document this dependency (in `setup.py`, `travis.yml`, the package install instructions).

JPEG I/O library

---

docs/develop.rst
docs/installation.rst

This pull request addresses issue #5.  It adds documentation on how to set up the `HIPS_EXTRA` environment variable.

Add documentation on HIPS_EXTRA environment variable

---

notes/announce-0.1.txt

I think in ~ a week we'll be ready for v0.1 with the hips package, i.e. have a first version of the `make_sky_image` high-level function working (see #30).
To prepare the release, I've written up a draft of the release announcements, to be sent to the astropy-dev mailing list (and which you can forward elsewhere if you think it's useful).
@tboch @adl1995 - Could you please read it over? You can either suggest changes via comments, or edit directly to propose some change.
@tboch - Do we need to state "this is not an officially maintained CDS package" or more explicitly acknowledge that CDS supported this by giving your time somehow? Or is it OK as-is?

Draft for v0.1 announcement email

---

hips/tiles/surveys.py
hips/tiles/tile.py

I would like to propose this solution to address #42 : suppress the warnings from invalid FITS tiles.
Since this is a "known issue" (or "known feature" if you like) for the FITS tiles from CDS, and every user will get one of these warnings per tile they fetch or read on the console, and there's nothing they can / should do about it except to ignore it, I think it is appropriate to suppress these warnings.
I'm not an expert on Python warnings, but I think / hope that this will have little other effect than suppressing the warnings we want to suppress, and to keep other warnings / errors intact.
@tboch - Assigning to you for review.
@adl1995 - I've also cleaned up the I/O functions a bit to:
* always use `with` statements to read / fetch, to avoid leaving open filehandles around
* removed …

Improve HiPS tile I/O

---

hips/draw/tests/test_simple.py
hips/tiles/tests/test_tile.py
hips/tiles/tile.py

This PR adds a test case for PNG tiles. The same code for jpg tiles is used for png.

Add test for PNG tiles

---

docs/getting_started.rst
hips/draw/tests/test_simple.py
hips/tiles/tests/test_tile.py
hips/utils/testing.py
hips/utils/tests/test_healpix.py
hips/utils/tests/test_wcs.py
hips/utils/wcs.py

Added a classmethod as mentioned in #39.

Add classmethod create_simple to WCSGeometry

---

hips/draw/simple.py
hips/draw/tests/test_simple.py
hips/tiles/surveys.py

As discussed in issue #62, I have added a test case of JPG tiles, which is passing. However, I haven't added a test case for PNG tiles, because the current survey only support FITS, JPG tiles.

Add support for RGB tiles

---

docs/plot_fits.py
hips/draw/simple.py
hips/draw/tests/test_simple.py
hips/utils/healpix.py
hips/utils/tests/test_healpix.py

As discussed in issue #57, I have reformatted the `SimpleTilePainter` class. I'm aware this still needs some changes, but this will provide us with a working ground. For now, I have commented out the `test_draw_sky_image` function as it is not currently usable.
@cdeil @tboch Please provide feedback on what needs to be changed.

Reformat SimpleTilePainter class

---

CHANGES.rst
docs/about.rst
docs/api.rst
docs/develop.rst
docs/drawing_algo.rst
docs/getting_started.rst
docs/index.rst
docs/installation.rst
docs/plot_jpg.py
docs/references.txt
hips/__init__.py
hips/draw/simple.py
hips/draw/tests/test_simple.py
hips/tiles/tests/test_surveys.py
hips/tiles/tests/test_tile.py
hips/tiles/tile.py
hips/utils/healpix.py
hips/utils/tests/test_healpix.py
hips/utils/tests/test_wcs.py
hips/utils/wcs.py
setup.cfg

This pull request contains some misc changes and cleanup I'd like to make before releasing v0.1:
@tboch - Do you want to review this today or are you already on vacation?

Misc changes / cleanup before v0.1

---

hips/draw/simple.py
hips/tiles/io.py
hips/tiles/surveys.py
hips/tiles/tests/test_io.py
hips/tiles/tests/test_surveys.py
hips/tiles/tests/test_tile.py
hips/tiles/tile.py
hips/utils/wcs.py

Improve tile I/O

---

hips/tiles/tests/test_tile.py
hips/tiles/tile.py

This PR implements the `HipsTile.from_numpy` method and adds a test.
For `JPEG` I'm not asserting on the output pixels, because it's not easily possible.
Maybe we'll implement tests for JPEG tile creation in the future.

Implement HipsTile.from_numpy and test

---

hips/draw/simple.py
hips/draw/tests/test_simple.py

@cdeil As discussed on Slack, I have updated the `dtype` so that RGB drawing works fine.

Fix RGB dtype issue

---

hips/tiles/surveys.py

I encountered this issue when playing with certain surveys that are missing the `hips_tile_width` property key, such as this one (http://alasky.u-strasbg.fr/PLANCK/R2/HFI_Color_353_545_857/properties). They simply failed when I tried to access the property, this PR will fix this issue.

Fix tile_width property in HipsSurveyProperties class

---

hips/draw/simple.py
hips/draw/tests/test_simple.py

As outlined in this Jupyter notebook (https://github.com/adl1995/HIPS-to-Py/blob/master/examples/JPG_tile_draw_issue.ipynb), I have added two methods for drawing markers and lines over an all-sky image.

Add methods for drawing markers over sky image

---

hips/draw/simple.py
hips/draw/tests/test_simple.py

This PR fixes the tile corner order in drawing for PNG and JPEG tiles.
Mentioned in #74 and also #18 .
I make a few images and they all looked OK now.

Fix tile corner order for PNG and JPEG

---

hips/tiles/tests/test_tile.py
hips/tiles/tile.py

As outlined in #83, I have added a property named `children` in `HipsTile` class, this splits the parent tile into four children tiles. I also added a some test cases for the first child.

Add property 'children' for creating four children tiles from parent tile

---

hips/draw/simple.py
hips/draw/tests/test_simple.py
hips/tiles/__init__.py
hips/tiles/allsky.py
hips/tiles/tests/test_allsky.py
hips/tiles/tests/test_tile.py
hips/tiles/tile.py
hips/utils/healpix.py
hips/utils/tests/test_healpix.py

This PR introduces support for all-sky combined tile images such as:
https://github.com/hipspy/hips-extra/blob/master/datasets/samples/FermiColor/Norder3/Allsky.jpg
I'm not happy at all with the implementation: to re-use the image I/O functionality, I had to sub-class
```
class HipsTileAllskyArray(HipsTile):
```
which is very weird.
I'm not sure yet what a good design is. Maybe move the image handling and I/O functionality from `HipsTile` to a `hips.utils.ImageFile` class, and introduce a separate `hips.utils.ImageArray` class which has a Numpy array data member instead of an encoded bytes attribute. Or get rid of those classes and instead use more functions, like they do in scikit-image. If you look at the tests here, you'll see that `HipsTileAllskyArray` duplicates a lot from `HipsTile` …

Add all-sky image class and update existing tile code

---

hips/draw/simple.py
hips/draw/tests/test_simple.py

As mentioned in issue #84, I have added two methods `to_split` and `_measure_tile_shape` which are used for checking whether a tile needs to be split or not. The next step is to perform the actual splitting and modify the projection part to take in the correct `tile_width` (half, in case a tile is split).

Add method to_split in SimpleTilePainter for checking whether to split a tile

---

docs/about.rst
docs/references.txt
hips/draw/simple.py
hips/tiles/allsky.py
hips/tiles/tests/test_allsky.py
hips/tiles/tests/test_tile.py
hips/tiles/tile.py

This PR improves the all-sky image implementation and tests to also work with FITS images.

Improve tile and allsky orientation handling

---

docs/getting_started.rst
docs/plot_fits.py
docs/plot_jpg.py
hips/draw/simple.py
hips/draw/tests/test_simple.py
hips/utils/wcs.py

As outlined in issue #80, I have added a class `HipsDrawResult`. This still needs more work, currently it only stores `image` and `geometry`.

Introduce class HipsDrawResult in simple.py

---

hips/utils/healpix.py
hips/utils/tests/test_healpix.py

This PR adds a `hips_tile_healpix_ipix_array` function, that is the key building block to convert between HEALPix pixels and HiPS tile pixels. I don't have time to continue with this and actually use it today, so I'll merge as-is and then continue with this in future PRs.
This is more or less my guess of how the HEALPix to HiPS tile pixel mapping works, it's not detailed in http://www.ivoa.net/documents/HiPS/20170519/REC-HIPS-1.0-20170519.pdf and I haven't debugged / tested it.

Add hips_tile_healpix_ipix_array function

---

docs/getting_started.rst
hips/draw/simple.py
hips/tiles/surveys.py
hips/tiles/tests/test_surveys.py

As outlined in #82 and during the telecon yesterday, I have added the option to create `HipsSurveyProperties` using a survey name.
@cdeil Currently, this is not implemented:
> 
> In addition, we might want to allow the geometry parameter in make_sky_image to be a dict, and if it is, call WCSGeometry.create_from_dict() for the user as a convenience. I.e. this would work:
> 
> ```
> geometry = dict(target='crab', fov='10 deg', frame='galactic')
> make_sky_image(geometry, hips_survey)
> 
> ```
Can this be part of a separate PR?

Add option to create HipsSurveyProperties from survey name

---

hips/draw/paint.py
hips/draw/ui.py
hips/utils/tests/test_wcs.py
hips/utils/wcs.py

As @cdeil mentioned in #82, I have added a classmethod `create_from_dict` in `WCSGeometry` class. Now the user can pass either a `dict` or a `WCSGeometry` object itself. There is also a convenience method `make` in `WCSGeometry` which creates the object from `dict` parameters, if required.

Add classmethod create_from_dict in WCSGeometry class

---

.travis.yml
docs/getting_started.rst
docs/installation.rst
docs/references.txt
hips/draw/paint.py
hips/draw/ui.py
setup.py

As mentioned in #80, I have added a progress bar support for fetching and drawing HiPS tiles. The progress bar is off by default, the result can be seen in this notebook: https://github.com/adl1995/HIPS-to-Py/blob/master/examples/Precise%20drawing-ICRS.ipynb
To achieve this, I had to make use of the `tqdm` module.

Add progress bar support for fetching and drawing HiPS tiles

---

.rtd-environment.yml
.travis.yml
docs/installation.rst
docs/references.txt
hips/draw/paint.py
hips/draw/tests/test_paint.py
hips/draw/tests/test_ui.py
hips/draw/ui.py
hips/tiles/__init__.py
hips/tiles/fetch.py
hips/tiles/tests/test_fetch.py
hips/utils/testing.py
setup.py

As the title states, HiPS tiles are now fetched asynchronously. I noted 4 seconds for tile fetching which previously took around 25 seconds at my end. For now, this is introduced in the `HipsPainter` class, but let me know if this needs to be refactored somewhere else.

Introduce asynchronous fetching of HiPS tiles

---

.gitignore
.travis.yml
CHANGES.rst
appveyor.yml
docs/conf.py
docs/installation.rst
docs/references.txt
hips/conftest.py
hips/draw/paint.py
hips/draw/tests/test_ui.py
hips/draw/ui.py
hips/tiles/tile.py
hips/utils/__init__.py
hips/utils/healpix.py
hips/utils/tests/test_healpix.py
setup.py

This is a first quick attempt to change the `hips` package from `healpy` over to the to-be Astropy healpix package (http://healpix.readthedocs.io/). The main motivation for the change is to support Windows, another motivation is to have an easier-to-install dependency (or no dependency at all if this gets merged as `astropy.healpix` into the core at some point).
This pull request is work in progress, it should only be merged after there has been a release and a conda package exists for the Astropy healpix package.
In addition, I'd like to remove `hips/utils/healpix.py` and change the callers to use the main Astropy healpix API, not the healpy-compatible API, and the dependency declaration in `setup.py` as well as the install docs need to be updated.
@astrofrog - For now, I see two issues …

Change from healpy to astropy-healpix

---

.rtd-environment.yml
README.rst
readthedocs.yml

This PR is updating readthedocs.yml to use astropy-healpix .
Really the main thing here is to see if the build / test works on Windows (see #3).

Update readthedocs.yml to use astropy-healpix

---

ah_bootstrap.py
hips/tiles/tile.py

This is an automated update of the astropy-helpers submodule to v3.0.1. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed. 
A full list of changes can be found in the [changelog](https://github.com/astropy/astropy-helpers/blob/v3.0.1/CHANGES.rst). 
*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @bsipocz or @astrofrog know!* 
Along with with the astropy core release v3.0, we have also started to release astropy-helpers v3.0.x versions. Similarly to the core package, these require Python 3.5+. We will open automated update PRs with astropy-helpers v3.0.x only for packages that specifically opt in for it when they start …

Update astropy-helpers to v3.0.1

---

hips/draw/healpix.py
hips/tiles/fetch.py
hips/tiles/survey.py

Python dicts are ordered since Python 3.6, and it will stay that way (see [here](https://mail.python.org/pipermail/python-dev/2017-December/151283.html)).
So removing `collections.OrderedDict` by `dict`.

Use dict (now ordered in Python 3.6+

---

hips/draw/tests/test_ui.py
hips/draw/ui.py

Following issue #127, this PR adds the `overwrite` parameter to `write_image` function, which defaults to `False`. For now, this parameter only works with FITS files, I'm not sure what's the default behavior of PIL for JPG and PNG files.
@cdeil - Should I include a test case for this by writing a same file twice?

Add overwrite option in write_image function for FITS files

---

docs/getting_started.rst
docs/plot_fits_astropy.py
hips/draw/ui.py

This PR updates the docs and adds a section named "Plot using Astropy visualization toolkit" in the "Getting started" page.
The [result.plot()](https://github.com/hipspy/hips/blob/master/hips/draw/ui.py#L124) method is also updated as it now uses a boolean `show_grid` to turn off the tile boundaries grid (Cf. #130).

Provide example on how to plot image using Astropy visualization toolkit

---

hips/tiles/survey.py

There's a fail in `TestHipsSurveyPropertiesList.test_table`:
https://travis-ci.org/hipspy/hips/jobs/467627256#L3839
I see the fail locally as well with latest Astropy.
It comes from here:
https://github.com/hipspy/hips/blob/e870e5c97a136810e857c676a65e6beb2bf1804f/hips/tiles/survey.py#L287-L302
I'll look into this issue tomorrow and fix it somehow.

TestHipsSurveyPropertiesList.test_table fail

---

hips/draw/paint.py

This should fix the following warning from Matplotlib:
```
MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance. In a future version, a new instance will always be created and returned. Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance. warnings.warn(message, mplDeprecation, stacklevel=1)
```

Avoid creating the Axes object in each iteration

---

hips/tiles/tests/test_tile.py
hips/tiles/tile.py

Today I wanted to make the `healpix_to_hips` work for RGB JPEG and RGBA PNG data. I'll make a pull request for that shortly.
However, I noticed that there seems to be a bug in our `HipsTile.from_numpy` or `HipsTile.to_numpy` for the RGB JPEG case. This PR shows the issue via a regression test. It works for FITS and also for RGBA PNG as expected.
Looking for old issues I saw #112, possibly this is the same issue. I did try adding `.copy` calls before and after the `flipud` calls in `from_numpy`, no change, so transposed Numpy arrays don't seem to be the issue.
@tboch and maybe if you have time @adl1995 or @adonath - If you have time, could you please have a look at this and comment if you have any idea?
This is blocking the work on HEALPix -> HiPS and the v0.3 release, so we should try to …

Add tests for HiPS tile <-> Numpy conversions
